name: Build Maui Windows

on:
  release:
    types:
      - published
  workflow_dispatch:
jobs:
  build-maui-win:
    runs-on: windows-latest  # MAUI build now runs on Windows
    
    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4

    - name: .NET SDK einrichten für MAUI
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'  # Setze hier die gewünschte .NET Version (9.0)

    - name: Install MAUI workloads
      run: dotnet workload install maui

    - name: Build MAUI project for Windows
      run: dotnet build ./piratechess_maui/piratechess_maui.csproj

    - name: Publish MAUI project for Windows (Single File)
      run: dotnet publish ./piratechess_maui/piratechess_maui.csproj -f net9.0-windows10.0.19041.0 --output ./publish/maui/win-x64 --self-contained false -r win-x64 /p:PublishSingleFile=true /p:DebugType=none

    - name: Umbenennen der MAUI Windows Version
      run: Rename-Item -Path ./publish/maui/win-x64/piratechess_maui.exe -NewName piratechess_maui-win-x64.exe

    - name: Release-Asset erstellen für MAUI
      uses: softprops/action-gh-release@v1
      with:
        files: 
          ./publish/maui/win-x64/piratechess_maui-win-x64.exe 
      if: ${{ github.event_name == 'release' || github.event_name == 'push' }}  # Only run on release or tag push
 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
