name: Build Winforms windows

on:
  release:
    types:
      - published
  workflow_dispatch:
  
jobs:
  build-winforms:
    runs-on: windows-latest

    steps:
    - name: Repository auschecken
      uses: actions/checkout@v4

    - name: .NET SDK einrichten für Winform
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0'  # Setze hier die gewünschte .NET Version (9.0)

    - name: Restore dependencies for WinForms
      run: dotnet restore ./piratechess_winform/piratechess_winform.csproj

    - name: Build WinForms project
      run: dotnet build ./piratechess_winform/piratechess_winform.csproj --configuration Release

    - name: Publish WinForms project 64-bit (Single File)
      run: dotnet publish piratechess_winform/piratechess_winform.csproj --configuration Release --output ./publish/win-x64 --self-contained false -r win-x64 /p:PublishSingleFile=true /p:DebugType=none 

    - name: Publish WinForms projects 32-bit (Single File)
      run: dotnet publish piratechess_winform/piratechess_winform.csproj --configuration Release --output ./publish/win-x86 --self-contained false -r win-x86 /p:PublishSingleFile=true /p:DebugType=none 
      
    - name: Umbenennen der 32-bit Version
      run: Rename-Item -Path ./publish/win-x86/piratechess_winform.exe -NewName piratechess_winform-win-x86.exe

    - name: Release-Asset erstellen
      uses: softprops/action-gh-release@v1
      with:
        files: ./publish/**/*.exe
      if: ${{ github.event_name == 'release' || github.event_name == 'push' }}  # Only run on release or tag push

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}